# Generated by Django 4.2.13 on 2024-05-21 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0002_alter_coinprice_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinPriceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='coins/prices/')),
                ('coin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coins.coin')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
