# Generated by Django 4.2.13 on 2024-05-22 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0003_coinpricefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='credits',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
