# Generated by Django 4.2.13 on 2024-05-21 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=128, null=True)),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'Gold'), (2, 'Silver')], null=True)),
                ('days_to_expire', models.PositiveIntegerField(null=True)),
            ],
            options={
                'ordering': ('level',),
            },
        ),
        migrations.AddField(
            model_name='user',
            name='credits',
            field=models.PositiveBigIntegerField(default=10),
        ),
        migrations.CreateModel(
            name='RegisteredSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('approved', 'approved'), ('rejected', 'rejected'), ('pending', 'pending'), ('requested', 'requested')], default='requested', max_length=15, null=True)),
                ('expire_at', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('credits', models.PositiveBigIntegerField(null=True)),
                ('credits_period', models.CharField(choices=[('daily', 'daily'), ('unlimited', 'unlimited')], default='daily', max_length=10)),
                ('credits_added', models.BooleanField(default=False)),
                ('subscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='accounts.subscription')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
