# Generated by Django 4.2.13 on 2024-05-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_registeredsubscription_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredsubscription',
            name='status',
            field=models.CharField(choices=[('requested', 'requested'), ('approved', 'approved'), ('rejected', 'rejected')], default='requested', max_length=15, null=True),
        ),
    ]
