# Generated by Django 4.2.13 on 2024-05-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_registeredsubscription_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='level',
            field=models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver')], max_length=10, null=True),
        ),
    ]
